[versions]
apache-http = "4.5.13"
bouncycastle = "1.70"
figuretech-hdwallet = "0.4.1"
grpc = "1.55.1"
kotlin = "1.9.10"
kotlinx-core = "1.6.4"
provenance-protos = "1.16.0"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

bouncycastle = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncycastle" }

figuretech-hdwallet = { module = "tech.figure.hdwallet:hdwallet", version.ref = "figuretech-hdwallet" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

grpc-alts = { module = "io.grpc:grpc-alts", version.ref = "grpc" }
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc" }

provenance-protos = { module = "io.provenance:proto-kotlin", version.ref = "provenance-protos" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-core" }

apache-http = { module = "org.apache.httpcomponents:httpclient", version.ref = "apache-http" }
